### ISSUE TITLE
after clone and installation

### ISSUE THREAD

**Issue by some81** [joaopaulomoraes/nextjs-with-redux-and-material-ui#21]
TypeError: Cannot read property 'dispatch' of undefined
    at Function.Index.getInitialProps (webpack-internal:///./pages/index.js:140:9)
    at Function.getInitialProps (webpack-internal:///./pages/_app.js:37:94)
    at loadGetInitialProps (/Users/some81/Desktop/work/nextjs-with-redux-and-material-ui/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/Users/some81/Desktop/work/nextjs-with-redux-and-material-ui/node_modules/next/dist/next-server/server/render.js:27:1572)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/some81/Desktop/work/nextjs-with-redux-and-material-ui/node_modules/next/dist/next-server/server/next-server.js:112:97
    at async /Users/some81/Desktop/work/nextjs-with-redux-and-material-ui/node_modules/next/dist/next-server/server/next-server.js:105:142
    at async DevServer.renderToHTMLWithComponents (/Users/some81/Desktop/work/nextjs-with-redux-and-material-ui/node_modules/next/dist/next-server/server/next-server.js:137:387)
    at async DevServer.renderToHTML (/Users/some81/Desktop/work/nextjs-with-redux-and-material-ui/node_modules/next/dist/next-server/server/next-server.js:138:610)
    at async DevServer.renderToHTML (/Users/some81/Desktop/work/nextjs-with-redux-and-material-ui/node_modules/next/dist/server/next-dev-server.js:36:578)
4. WrappedApp created new store with withRedux(_App) { initialState: undefined, initialStateFromGSPorGSSR: undefined }
4. WrappedApp created new store with withRedux(_App) { initialState: undefined, initialStateFromGSPorGSSR: undefined }

**Comment by joaopaulomoraes** [comment]
Hi, there!

I followed the steps in the document and could not get this error.

I think you maybe updated some packages, like redux. In this case, you need to reconfigure the project based on the version used.

This project is just an initial boilerplate/example of how to make use of the aforementioned tools.

Anyway, thanks for the feedback.
